- index.ts
- output.test.ts
- output.ts
These methods were deprecated. We now remove them and will release a `0.4.0` of this package without them.
> Remove deprecated output methods

- .eslintrc.js
- .github/workflows/tests.yml
- .gitignore
- package.json
Updates our test suite to run on all versions of Node.js that are currently supported on Airplane, [except Node 12 and 15](https://linear.app/airplane/issue/AIR-3536/deprecate-node-12-and-15). It also adds [Node 18](https://linear.app/airplane/issue/AIR-3549/support-node-18) given we'll be adding support for it to Airplane soon.
We don't include Node 12 support here since `node-fetch` uses the `node:` protocol (e.g. `node:http`) which is only available in ESM mode in Node 12. For folks using the Node 12 runtime, they can continue to use `v0.1.2`.
Based on: https://github.com/sindresorhus/got/blob/main/.github/workflows/main.yml
> Run tests on all node versions

- .github/CONTRIBUTING.md
- package.json
`v0.2.0-0` did not include the `dist/` folder. I tweaked the release process to automatically run `yarn build` to avoid this issue.
I'll release as `v0.2.0-1` once merged.
> Fix missing `dist` folder in prerelease

- .github/CONTRIBUTING.md
Turns out `--publish` does not override `--preview=true`.
> Fix `publish` command

- fetch.ts
- package.json
- yarn.lock
Use cross fetch which works in browser (uses [GitHub's WHATWG Fetch polyfill](https://github.com/github/fetch)) or node (uses node-fetch).
This should just wrap the two libraries and not do anything extra. Later, we might want to consider writing our own impl that just uses browser fetch instead of the polyfill to reduce code size
> Use cross fetch instead of node-fetch

- tasks.ts
This code returns a reference error in non node environemnts because process does not exist globally. We need to use a `typeof` check which doesn't throw a reference error when using process.
> Process does not exist in non-node

- tasks.ts
Now that we monkey patch `process.env` to make it accessible in the SDK, we can use the `AIRPLANE_RUNTIME` env var to determine whether or not to durably execute a task or execute it the standard way.
Related: https://github.com/airplanedev/lib/pull/159
Tested locally by deploying/running a workflow task without the runtime specified in ExecuteOptions.
> Use AIRPLANE_RUNTIME env var to determine internal execute method

- internal/api/fetcher.test.ts
- internal/api/fetcher.ts
In production, views rely on session cookies to authn with the API - they do not explicitly pass in an authn token or api key. This error precludes this from working.
> Remove error if no authn is provided

- .github/CONTRIBUTING.md
- .github/workflows/tests.yml
- package.json
- yarn.lock
We were having issues with our previous release process that used `np`. First, it depended on engineers pushing a commit to `main` to change the version field in `package.json`. This does not work with our branch protection rules. Second, it does not support deploying a sub-directory. We build our TS into the `dist` folder and want the built code to be the root of the released package (so that users can import `airplane/sql` which depends on a `sql.js` file in the root of the package). There is a `contents` field from `np` that supports this , but I couldn't get this to work the way we needed.
This PR moves the release process to GHA. It's much more convenient -- just merge a PR that bumps the version in the `package.json` and it will automatically publish. I tested this by releasing …
> Replace `np` with automatic deployments from GHA

- index.ts
- input.ts
- internal/api/client.ts
- internal/api/types.ts
- internal/builtins/email.ts
- internal/builtins/mongodb.ts
- internal/builtins/rest.ts
- internal/builtins/slack.ts
- internal/builtins/sql.ts
- internal/execute.ts
- internal/input/index.ts
- internal/input/slug.test.ts
- internal/input/slug.ts
- internal/runtime/index.ts
- internal/runtime/standard.ts
- internal/runtime/workflow.ts
- package.json
Adds support for a single type of prompt: text strings. Follow-up PRs will add the remainder of the prompt kinds.
cc @kellymtrinh 
Resolves AIR-4114
> Add basic prompts: `airplane.input.text` 

- internal/builtins/builtins.test.ts
- internal/builtins/builtins.ts
- internal/builtins/email.ts
- internal/builtins/mongodb.ts
- internal/builtins/rest.ts
- internal/builtins/sql.ts
Resolves AIR-4143
Switches over from resource ids to aliases now that resource attachments are out. Users will need to attach the resource and then refer to the resource via alias in all builtin functions.
> Use resource aliases in builtin functions

- internal/output.ts
- internal/runtime/index.ts
- internal/runtime/standard.ts
- internal/runtime/workflow.ts
- package.json
This PR adds workflow task support for the `setOutput` and `appendOutput` methods of our SDK - we move `logChunks` to the runtime interface because its implementation varies depending on whether the task is a standard or workflow task. 
For standard tasks, we log to stdout and utilize the uuid package to generate chunk keys. For workflow tasks, however, we must log to a sink , and also use Temporal's `uuid` method, which generates UUIDs with a seed that is derived from the workflow id, and so guarantees workflow determinism.
Also changes any references of `substr` -> `substring` since the former has been deprecated.
> Add support for setting output in workflow tasks

- internal/runtime/workflow.ts
- package.json
We've modified our API to send signals with camel case field names, in accordance with standard JSON field names - this PR changes the signals' types to use these updated field names.
> Use camel case field names in signal

- internal/errors.test.ts
- internal/errors.ts
- internal/execute.ts
When a run fails (or is cancelled), throw an error that a user can optionally catch. IOW, by default a failed child run will fail the parent run.
Resolves AIR-4093
> Throw error when child runs fail

- package.json
- yarn.lock
This PR upgrades the `temporalio` package to 1.0.0-rc.0, which includes various fixes in the SDK - in particular, I'd like to utilize a change that fixes replay logic so that we don't need to enable the `callDuringReplay` flag when a workflow gets interrupted, which potentially causes duplicate Temporal logs: https://github.com/temporalio/sdk-typescript/issues/667.
> Upgrade temporal package to GA version

- internal/runtime/workflow.ts
By default, temporal activities are retried indefinitely: https://docs.temporal.io/retry-policies/#default-values-for-retry-policy - this is not behavior we'd like since that means multiple child runs could get created in the case of transient temporal failures. In that case, we'd like to fail the workflow entirely - this PR sets the maximum number of attempts in any Node SDK activity to be at most 1 so that retries never occur.
> Don't retry temporal activities

- internal/runtime/dev.ts
- internal/runtime/index.ts
Adds a new runtime type, `dev`, to the Node SDK - previously, `airplane dev` was using the standard runtime methods (successfully); however, this PR formalizes the notion of a new dev runtime with some minor differences from the standard runtime. For example, we don't need to poll for the run to finish - in our local dev api server implementation of `/tasks/execute`, we set the status of the run so there's no need to wait for `/runs/get` to return a result. For now, the `prompt` and `logChunks` methods just reference the standard runtime implementation.
> Add dev runtime

- package.json
- yarn.lock
We are getting warning on dep install that we should be using nested temporal packages:
Switch to using the nested workflow package. 
I'm unsure how to manually test this - any guidance here?
Unrelated, but we need to work on the build system for this repo. It doesn't produce esm modules so it isn't tree shakeable - this is causing consumers (like views) to import all of the code even though we are only using part of the code (e.g. views imports temporal).
> Import nested temporal package

- internal/config.ts
- package.json
The standard runtime can set the value of the runtime variable to a blank string. Check instead that the runtime env var is defined and not "dev".
> Fix airplane runtime detection

- internal/config.ts
We don't want to run the function locally and instead always call the execute api. Unittests can mock the api calls to run properly.
> Remove branching behavior for task execute depending on runtime
